project:
  type: website
  output-dir: docs  # docs directory of master branch

website:
  title: "My Website"
  
  search: false
  
  navbar:
    background: "primary" # “primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color
    foreground: "#ffffff"
    
    search: false
    
    right:
      - href: index.qmd
        text: Home
      - href: themes.qmd
        text: Themes
      - href: fonts.qmd
        text: Fonts
      - href: content.qmd
        text: Content
      - text: Menu
        menu:
        - text: Images Layout 
          href: layout_image.qmd
        - text: Images Gallery            
          href: gallery.qmd
        - text: Charts
          href: charts.qmd
        - text: Google Sheet
          href: google_sheet.qmd
        - text: Callout Blocks
          href: callout_blocks.qmd
        - text: Text
          href: text.qmd
        - text: Hyperlinks
          href: hyperlinks.qmd
      - href: posts.qmd
        text: Blog Posts
      - href: about.qmd
        text: About
        
  page-footer: 
    center: "© 2025. Website made with [Quarto](https://quarto.org/)."
    background: light


format:
  html:
    theme:
      - cosmo
      - css/roboto.css   # downloaded font
      - theme_custom.scss
#    css: styles.css        # empty
    mainfont: "Roboto"
    fontsize: 1.1em
    toc: true
    
# embed-resources: true

